name: Test and build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - uses: arduino/setup-protoc@v3
    - name: Run the test suite
      run: cargo test --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Run clippy linter
      run: cargo clippy --all-targets
    - name: Run formatter
      run: cargo fmt --check
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - name: Run the build
      run: cargo build

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    - uses: arduino/setup-protoc@v3
    - name: Use pbuildrs to compile protobuf IDL
      run: |
        cargo run -- --build-client --build-server --with-well-known-types \
          --with-file-descriptor-set example/src/fds.bin \
          --output example/src/autogen/ ./proto/
    - name: Verify that generated code actually works
      run: cargo test --all-features
      working-directory: example/
